# Generated by Django 4.2.30 on 2026-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('certification_status', models.CharField(choices=[('PENDING', 'Pending'), ('CERTIFIED', 'Certified'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('certification_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.memberprofile')),
                ('specialties', models.ManyToManyField(to='registry.specialty')),
            ],
        ),
    ]
