# Generated by Django 4.2.30 on 2026-04-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('partner_type', models.CharField(choices=[('CLINIC', 'Medical Center / Clinic'), ('UNIVERSITY', 'Educational Institution'), ('NGO', 'Non-Profit Organization'), ('SCHOOL', 'School / Training Center'), ('CORPORATE', 'Corporate Partner')], default='CLINIC', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_since', models.DateField(blank=True, null=True)),
                ('gna_partner_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, help_text='e.g. 40 hours, 3 months', max_length=100)),
                ('format', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='registry.accreditedpartner')),
            ],
        ),
    ]
