# Generated by Django 4.2.7 on 2026-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to image (e.g. Unsplash)', max_length=500, null=True),
        ),
    ]
